import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Home.module.css'

import { useRouter } from 'next/router'
import ClientOnly from "../../../components/ClientOnly";
import Videos from "../../../components/Videos";
import Navigation from "../../../components/Navigation";
import React from "react";
import digitalIcon from '../../../public/OriginsLogo.png'

const VideoTag = () => {
    const router = useRouter()
    const { tag } = router.query

    return (
        <div className={styles.container}>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation />

            <main className={styles.main + " width-standard"}>
                <ClientOnly>
                    <Videos tags={tag} similar={false}/>
                </ClientOnly>
            </main>

            <footer className={styles.footer + " width-standard"}>
                <a rel="icon" href="/">
                    <Image src={digitalIcon} alt="Origins Logo" width={200} height={90} />
                </a>
            </footer>
        </div>
    )
}

export default VideoTag